class FortuneCookie
  FORTUNES = [
    "Go to bed with itchy bum, wake up with smelly finger.",
    "A good way to keep healthy is to eat more Chinese food.",
    "You learn fomr your mistakes... You will learn a lot today",
    "Ignore all previous fortunes.",
    "Your fortune resides in another cookie.",
    "Do not mistake temptation for opportunity.",
    "Some men dream of fortunes, others dream of cookies.",
    "You will be hungry again in one hour.",
    "I cannot help you, for I am just a cookie.",
    "A tub and a rub will change your day",
    "If you can read this, you are literate, congrats.",
    "Oops, wrong cookie.",
    "That wasn't chicken.",
    "Never wear your best pants when you go to fight for freedom.",
    "It's about time I got out of that cookie.",
    "Help, I am being held prisoner in a Chinese bakery.",
    "You love Chinese food.",
    "You will regret your decision for dinner tonight.",
    "Your friends secretly agree that your head is too small for your body.",
    "Accept that some days you're the pigeon and some days you're the statue.",
    "Don't fry bacon in the nude.",
    "When everything's coming your way, you're probably in the wrong lane.",
    "Meh.",
    "Hearty laughter is a good way to jog internally without having to go outdoors.",
    "Wouldn't it be ironic to die in a living room.",
    "You have rice in your teeth.",
    "Some fortune cookies contain no fortune.",
    "Marriage lets you annoy one special person for the rest of your life.",
    "Some fortune cookies contain no fortune.",
    "Your mind is filled with nothing.",
    "Never tease an armed midget with a high five.",
    "Life will be happy, until the end when you'll pee yourself a lot.",
    "A thrilling time is in your immediate future.",
    "He who laughs lasts is laughing at you.",
    "Someone has Googled you recently.",
    "Don't eat any Chinese food today or you'll be sick.",
    "A man with brown eyes has a surprise for you.",
    "You are not illiterate.",
    "An alien of some sort will be appearing to you shortly!",
    "Don't panic.",
    "It could be better, but it's good enough.",
    "You will find a thing and it will be important.",
    "Two days from now, tomorrow will be yesterday.",
    "When chosen for jury duty, tell the judge about this fortune.",
    "You are cleverly disguised as a responsible adult.",
    "Drive like hell and you will get there.",
    "Person who eat fortune cookie gets lousy dessert.",
    "You will soon have an out of money exprience.",
    "He who dies with most money, still dies.",
    "Two can live as cheaply as one, for half as long.",
    "Life is a sexually transmitted condition.",
    "Give person fish, he eat for a day. Teach person to fish, he smell funny always.",
    "Person who argues with idiot is taken for fool.",
    "Look before you leap. Or wear a parachute.",
    "The end is near, mine as well have dessert.",
    "This fortune is no good. Try another.",
    "Run.",
    "I cannot help you, for I'm just a cookie.",
    "Made in the USA.",
    "Stop procrastinating...starting tomorrow",
    "You pet is planning to eat you.",
    "Don't trust your cat.",
    "Don't be a dick.",
    "Ask your mom.",
    "A lucrative career change awaits. Have you considered gangsta rap?",
    "Ignore previous cookie."
  ]

  def self.random_fortune
    random = Random.new
    random_fortune = random.rand(FORTUNES.length - 1)
    FORTUNES[random_fortune]
  end
end
